#!/usr/bin/env bash
mkdir -p build/win32
mkdir -p build/macos
npx pkg . --out-path build/win32 --targets win
npx pkg . --out-path build/macos --targets macos


if [ ! -f node_modules/sqlite3/lib/binding/node-v57-win32-ia32/node_sqlite3.node ]; then
    npx node-pre-gyp install --directory=./node_modules/sqlite3 --target_platform=win32 --target_arch=ia32
fi
cp node_modules/sqlite3/lib/binding/node-v57-win32-ia32/node_sqlite3.node build/win32
cp node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node build/macos/